services:
  postgres:
    image: postgres:15
    container_name: sirius-postgres
    restart: always

    environment:
      POSTGRES_DB: sirius
      POSTGRES_USER: HMS_sirius
      POSTGRES_PASSWORD: HMS_sirius

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: