@baseUrl = http://localhost:8080

@hotelUrl = {{baseUrl}}/api/hotels
@roomCategoryUrl = {{baseUrl}}/api/room-category
@roomUrl = {{baseUrl}}/api/rooms
@rateUrl = {{baseUrl}}/api/rates
@priceUrl = {{baseUrl}}/api/prices
@profileUrl = {{baseUrl}}/api/profiles
@reservationUrl = {{baseUrl}}/api/reservations
@folioUrl = {{baseUrl}}/api/folios
@accrualUrl = {{baseUrl}}/api/accruals
@paymentUrl = {{baseUrl}}/api/payments


### AUTH

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123456"
}

> {%
    client.test("Login successful", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.token !== null);
    client.global.set("token", response.body.token);
%}


### HOTEL

POST {{hotelUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "hotelName": "Olga Grand Hotel",
  "description": "Luxury hotel in Kozyn",
  "phone": "+380501234567",
  "email": "olga.grand.hotel@gmail.com",
  "address": "Kozyn, Kyiv Region",
  "checkInTime": "14:00:00",
  "checkOutTime": "12:00:00"
}

> {%
    client.test("Hotel created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.global.set("hotelId", response.body.id);
%}


### HOTEL BY ID

GET {{hotelUrl}}/{{hotelId}}
Authorization: Bearer {{token}}

> {%
    client.test("Hotel found", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.id == client.global.get("hotelId"));
%}


### HOTEL BY NAME

GET {{hotelUrl}}/by-name?name=Olga%20Grand%20Hotel
Authorization: Bearer {{token}}

> {%
    client.test("Hotel found by name", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.hotelName === "Olga Grand Hotel");
%}


### STANDARD CATEGORY

POST {{roomCategoryUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Standard",
  "description": "Standard room",
  "countOfBeds": 2,
  "hotelId": {{hotelId}}
}

> {%
    client.test("Standard category created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("standardCategoryId", response.body.id);
%}


### SUPERIOR CATEGORY

POST {{roomCategoryUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Superior",
  "description": "Superior room",
  "countOfBeds": 2,
  "hotelId": {{hotelId}}
}

> {%
    client.test("Superior category created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("superiorCategoryId", response.body.id);
%}


### JUNIOR SUITE CATEGORY

POST {{roomCategoryUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Junior Suite",
  "description": "Junior Suite room",
  "countOfBeds": 2,
  "hotelId": {{hotelId}}
}

> {%
    client.test("Junior Suite category created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("juniorSuiteCategoryId", response.body.id);
%}


### SUITE CATEGORY

POST {{roomCategoryUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Suite",
  "description": "Suite room",
  "countOfBeds": 2,
  "hotelId": {{hotelId}}
}

> {%
    client.test("Suite category created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("suiteCategoryId", response.body.id);
%}


### KOZYN CORNER CATEGORY

POST {{roomCategoryUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Kozyn Corner",
  "description": "Premium corner room",
  "countOfBeds": 2,
  "hotelId": {{hotelId}}
}

> {%
    client.test("Kozyn Corner category created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("kozynCornerCategoryId", response.body.id);
%}


### ROOM 101

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "101",
  "floor": 1,
  "status": "AVAILABLE",
  "roomView": "CITY",
  "hotelId": {{hotelId}},
  "categoryId": {{standardCategoryId}}
}

> {%
    client.test("Room 101 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room101Id", response.body.id);
%}


### ROOM 102

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "102",
  "floor": 1,
  "status": "AVAILABLE",
  "roomView": "GARDEN",
  "hotelId": {{hotelId}},
  "categoryId": {{standardCategoryId}}
}

> {%
    client.test("Room 102 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room102Id", response.body.id);
%}


### ROOM 103

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "103",
  "floor": 1,
  "status": "AVAILABLE",
  "roomView": "STREET",
  "hotelId": {{hotelId}},
  "categoryId": {{standardCategoryId}}
}

> {%
    client.test("Room 103 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room103Id", response.body.id);
%}


### ROOM 201

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "201",
  "floor": 2,
  "status": "AVAILABLE",
  "roomView": "CITY",
  "hotelId": {{hotelId}},
  "categoryId": {{superiorCategoryId}}
}

> {%
    client.test("Room 201 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room201Id", response.body.id);
%}


### ROOM 202

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "202",
  "floor": 2,
  "status": "AVAILABLE",
  "roomView": "GARDEN",
  "hotelId": {{hotelId}},
  "categoryId": {{superiorCategoryId}}
}

> {%
    client.test("Room 202 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room202Id", response.body.id);
%}


### ROOM 301

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "301",
  "floor": 3,
  "status": "AVAILABLE",
  "roomView": "CITY",
  "hotelId": {{hotelId}},
  "categoryId": {{juniorSuiteCategoryId}}
}

> {%
    client.test("Room 301 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room301Id", response.body.id);
%}


### ROOM 302

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "302",
  "floor": 3,
  "status": "AVAILABLE",
  "roomView": "GARDEN",
  "hotelId": {{hotelId}},
  "categoryId": {{juniorSuiteCategoryId}}
}

> {%
    client.test("Room 302 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room302Id", response.body.id);
%}


### ROOM 401

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "401",
  "floor": 4,
  "status": "AVAILABLE",
  "roomView": "CITY",
  "hotelId": {{hotelId}},
  "categoryId": {{suiteCategoryId}}
}

> {%
    client.test("Room 401 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room401Id", response.body.id);
%}


### ROOM 402

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "402",
  "floor": 4,
  "status": "AVAILABLE",
  "roomView": "GARDEN",
  "hotelId": {{hotelId}},
  "categoryId": {{suiteCategoryId}}
}

> {%
    client.test("Room 402 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room402Id", response.body.id);
%}


### ROOM 404

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "404",
  "floor": 4,
  "status": "AVAILABLE",
  "roomView": "PANORAMIC",
  "hotelId": {{hotelId}},
  "categoryId": {{kozynCornerCategoryId}}
}

> {%
    client.test("Room 404 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room404Id", response.body.id);
%}


### ALL ROOMS

GET {{roomUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("All rooms loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body !== null);
%}


### BAR STANDARD

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR Standard",
  "description": "Best Available Rate Standard",
  "currency": "UAH",
  "categoryId": {{standardCategoryId}},
  "price": 5000.00,
  "active": true
}

> {%
    client.test("BAR Standard created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("barStandardRateId", response.body.id);
%}


### BAR SUPERIOR

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR Superior",
  "description": "Best Available Rate Superior",
  "currency": "UAH",
  "categoryId": {{superiorCategoryId}},
  "price": 6000.00,
  "active": true
}

> {%
    client.test("BAR Superior created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("barSuperiorRateId", response.body.id);
%}


### BAR JUNIOR SUITE

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR Junior Suite",
  "description": "Best Available Rate Junior Suite",
  "currency": "UAH",
  "categoryId": {{juniorSuiteCategoryId}},
  "price": 9000.00,
  "active": true
}

> {%
    client.test("BAR Junior Suite created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("barJuniorSuiteRateId", response.body.id);
%}


### BAR SUITE

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR Suite",
  "description": "Best Available Rate Suite",
  "currency": "UAH",
  "categoryId": {{suiteCategoryId}},
  "price": 10000.00,
  "active": true
}

> {%
    client.test("BAR Suite created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("barSuiteRateId", response.body.id);
%}


### BAR KOZYN CORNER

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR Kozyn Corner",
  "description": "Best Available Rate Kozyn Corner",
  "currency": "UAH",
  "categoryId": {{kozynCornerCategoryId}},
  "price": 15000.00,
  "active": true
}

> {%
    client.test("BAR Kozyn Corner created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("barKozynCornerRateId", response.body.id);
%}


### BAR10 STANDARD

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR10 Standard",
  "description": "Best Available Rate with 10 percent discount",
  "currency": "UAH",
  "categoryId": {{standardCategoryId}},
  "price": 4500.00,
  "active": true
}

> {%
    client.test("BAR10 Standard created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("bar10StandardRateId", response.body.id);
%}


### BAR10 SUPERIOR

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR10 Superior",
  "description": "Best Available Rate with 10 percent discount",
  "currency": "UAH",
  "categoryId": {{superiorCategoryId}},
  "price": 5400.00,
  "active": true
}

> {%
    client.test("BAR10 Superior created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("bar10SuperiorRateId", response.body.id);
%}


### BAR10 JUNIOR SUITE

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR10 Junior Suite",
  "description": "Best Available Rate with 10 percent discount",
  "currency": "UAH",
  "categoryId": {{juniorSuiteCategoryId}},
  "price": 8100.00,
  "active": true
}

> {%
    client.test("BAR10 Junior Suite created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("bar10JuniorSuiteRateId", response.body.id);
%}


### BAR10 SUITE

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR10 Suite",
  "description": "Best Available Rate with 10 percent discount",
  "currency": "UAH",
  "categoryId": {{suiteCategoryId}},
  "price": 9000.00,
  "active": true
}

> {%
    client.test("BAR10 Suite created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("bar10SuiteRateId", response.body.id);
%}


### BAR10 KOZYN CORNER

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR10 Kozyn Corner",
  "description": "Best Available Rate with 10 percent discount",
  "currency": "UAH",
  "categoryId": {{kozynCornerCategoryId}},
  "price": 13500.00,
  "active": true
}

> {%
    client.test("BAR10 Kozyn Corner created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("bar10KozynCornerRateId", response.body.id);
%}


### PRICE BAR STANDARD

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{barStandardRateId}},
  "roomCategoryId": {{standardCategoryId}},
  "amount": 5000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("Standard price created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("barStandardPriceId", response.body.id);
%}


### PRICE BAR SUPERIOR

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{barSuperiorRateId}},
  "roomCategoryId": {{superiorCategoryId}},
  "amount": 6000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("Superior price created", function () {
        client.assert(response.status === 201);
    });
%}


### PRICE BAR JUNIOR SUITE

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{barJuniorSuiteRateId}},
  "roomCategoryId": {{juniorSuiteCategoryId}},
  "amount": 9000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("Junior Suite price created", function () {
        client.assert(response.status === 201);
    });
%}


### PRICE BAR SUITE

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{barSuiteRateId}},
  "roomCategoryId": {{suiteCategoryId}},
  "amount": 10000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("Suite price created", function () {
        client.assert(response.status === 201);
    });
%}


### PRICE BAR KOZYN CORNER

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{barKozynCornerRateId}},
  "roomCategoryId": {{kozynCornerCategoryId}},
  "amount": 15000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("Kozyn Corner price created", function () {
        client.assert(response.status === 201);
    });
%}


### PRICE BAR10 STANDARD

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{bar10StandardRateId}},
  "roomCategoryId": {{standardCategoryId}},
  "amount": 4500.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR10 Standard price created", function () {
        client.assert(response.status === 201);
    });
%}


### PRICE BAR10 SUPERIOR

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{bar10SuperiorRateId}},
  "roomCategoryId": {{superiorCategoryId}},
  "amount": 5400.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR10 Superior price created", function () {
        client.assert(response.status === 201);
    });
%}


### PRICE BAR10 JUNIOR SUITE

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{bar10JuniorSuiteRateId}},
  "roomCategoryId": {{juniorSuiteCategoryId}},
  "amount": 8100.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR10 Junior Suite price created", function () {
        client.assert(response.status === 201);
    });
%}


### PRICE BAR10 SUITE

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{bar10SuiteRateId}},
  "roomCategoryId": {{suiteCategoryId}},
  "amount": 9000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR10 Suite price created", function () {
        client.assert(response.status === 201);
    });
%}


### PRICE BAR10 KOZYN CORNER

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{bar10KozynCornerRateId}},
  "roomCategoryId": {{kozynCornerCategoryId}},
  "amount": 13500.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR10 Kozyn Corner price created", function () {
        client.assert(response.status === 201);
    });
%}


### PROFILE 1

POST {{profileUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Vlad",
  "lastName": "Kovalenko",
  "middleName": "Testovych",
  "phoneNumber": "+380501234568",
  "email": "vlad.olga.{{hotelId}}@gmail.com",
  "gender": "MALE",
  "address": "Kyiv, Ukraine",
  "guestDocument": {
    "documentType": "ID_CARD",
    "documentNumber": "ID{{hotelId}}001",
    "issueDate": "2021-01-01",
    "expiryDate": "2031-01-01"
  }
}

> {%
    client.test("Profile 1 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("profile1Id", response.body.id);
%}


### PROFILE 2

POST {{profileUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith",
  "middleName": "Testovych",
  "phoneNumber": "+380501234569",
  "email": "john.olga.{{hotelId}}@gmail.com",
  "gender": "MALE",
  "address": "London, United Kingdom",
  "guestDocument": {
    "documentType": "PASSPORT",
    "documentNumber": "PS{{hotelId}}002",
    "issueDate": "2020-02-01",
    "expiryDate": "2030-02-01"
  }
}

> {%
    client.test("Profile 2 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("profile2Id", response.body.id);
%}


### PROFILE 3

POST {{profileUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Anna",
  "lastName": "Smith",
  "middleName": "Testovych",
  "phoneNumber": "+380501234570",
  "email": "anna.olga.{{hotelId}}@gmail.com",
  "gender": "FEMALE",
  "address": "Kyiv, Ukraine",
  "guestDocument": {
    "documentType": "PASSPORT",
    "documentNumber": "PS{{hotelId}}003",
    "issueDate": "2020-03-01",
    "expiryDate": "2030-03-01"
  }
}

> {%
    client.test("Profile 3 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("profile3Id", response.body.id);
%}


### RESERVATION 1 - STANDARD

POST {{reservationUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomId": {{room101Id}},
  "rateId": {{barStandardRateId}},
  "primaryGuestId": {{profile1Id}},
  "guestIds": [
    {{profile1Id}},
    {{profile2Id}}
  ],
  "checkInDate": "2026-09-25",
  "checkOutDate": "2026-09-28",
  "adults": 2,
  "children": 0
}

> {%
    client.test("Reservation 1 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.assert(response.body.folioId !== null);

    client.global.set("reservation1Id", response.body.id);
    client.global.set("folio1Id", response.body.folioId);
%}


### RESERVATION 2 - SUPERIOR

POST {{reservationUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomId": {{room201Id}},
  "rateId": {{barSuperiorRateId}},
  "primaryGuestId": {{profile2Id}},
  "guestIds": [
    {{profile2Id}},
    {{profile3Id}}
  ],
  "checkInDate": "2026-09-25",
  "checkOutDate": "2026-09-27",
  "adults": 2,
  "children": 0
}

> {%
    client.test("Reservation 2 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.assert(response.body.folioId !== null);

    client.global.set("reservation2Id", response.body.id);
    client.global.set("folio2Id", response.body.folioId);
%}


### RESERVATION 3 - JUNIOR SUITE

POST {{reservationUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomId": {{room301Id}},
  "rateId": {{barJuniorSuiteRateId}},
  "primaryGuestId": {{profile3Id}},
  "guestIds": [
    {{profile3Id}}
  ],
  "checkInDate": "2026-09-25",
  "checkOutDate": "2026-09-26",
  "adults": 1,
  "children": 0
}

> {%
    client.test("Reservation 3 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.assert(response.body.folioId !== null);

    client.global.set("reservation3Id", response.body.id);
    client.global.set("folio3Id", response.body.folioId);
%}


### RESERVATION 4 - SUITE

POST {{reservationUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomId": {{room401Id}},
  "rateId": {{barSuiteRateId}},
  "primaryGuestId": {{profile1Id}},
  "guestIds": [
    {{profile1Id}},
    {{profile3Id}}
  ],
  "checkInDate": "2026-09-28",
  "checkOutDate": "2026-10-02",
  "adults": 2,
  "children": 0
}

> {%
    client.test("Reservation 4 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.assert(response.body.folioId !== null);

    client.global.set("reservation4Id", response.body.id);
    client.global.set("folio4Id", response.body.folioId);
%}


### RESERVATION 5 - KOZYN CORNER

POST {{reservationUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomId": {{room404Id}},
  "rateId": {{barKozynCornerRateId}},
  "primaryGuestId": {{profile2Id}},
  "guestIds": [
    {{profile2Id}}
  ],
  "checkInDate": "2026-09-25",
  "checkOutDate": "2026-09-30",
  "adults": 1,
  "children": 0
}

> {%
    client.test("Reservation 5 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.assert(response.body.folioId !== null);

    client.global.set("reservation5Id", response.body.id);
    client.global.set("folio5Id", response.body.folioId);
%}


### RESERVATION 6 - STANDARD

POST {{reservationUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomId": {{room102Id}},
  "rateId": {{barStandardRateId}},
  "primaryGuestId": {{profile3Id}},
  "guestIds": [
    {{profile3Id}},
    {{profile2Id}}
  ],
  "checkInDate": "2026-10-01",
  "checkOutDate": "2026-10-05",
  "adults": 2,
  "children": 0
}

> {%
    client.test("Reservation 6 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.assert(response.body.folioId !== null);

    client.global.set("reservation6Id", response.body.id);
    client.global.set("folio6Id", response.body.folioId);
%}


### RESERVATION 7 - STANDARD

POST {{reservationUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomId": {{room103Id}},
  "rateId": {{barStandardRateId}},
  "primaryGuestId": {{profile1Id}},
  "guestIds": [
    {{profile1Id}}
  ],
  "checkInDate": "2026-09-26",
  "checkOutDate": "2026-09-29",
  "adults": 1,
  "children": 0
}

> {%
    client.test("Reservation 7 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.assert(response.body.folioId !== null);

    client.global.set("reservation7Id", response.body.id);
    client.global.set("folio7Id", response.body.folioId);
%}


### RESERVATION 8 - SUPERIOR

POST {{reservationUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomId": {{room202Id}},
  "rateId": {{barSuperiorRateId}},
  "primaryGuestId": {{profile2Id}},
  "guestIds": [
    {{profile2Id}},
    {{profile3Id}}
  ],
  "checkInDate": "2026-09-29",
  "checkOutDate": "2026-10-03",
  "adults": 2,
  "children": 0
}

> {%
    client.test("Reservation 8 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.assert(response.body.folioId !== null);

    client.global.set("reservation8Id", response.body.id);
    client.global.set("folio8Id", response.body.folioId);
%}


### RESERVATION 9 - JUNIOR SUITE

POST {{reservationUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomId": {{room302Id}},
  "rateId": {{barJuniorSuiteRateId}},
  "primaryGuestId": {{profile3Id}},
  "guestIds": [
    {{profile3Id}},
    {{profile1Id}}
  ],
  "checkInDate": "2026-10-03",
  "checkOutDate": "2026-10-07",
  "adults": 2,
  "children": 0
}

> {%
    client.test("Reservation 9 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.assert(response.body.folioId !== null);

    client.global.set("reservation9Id", response.body.id);
    client.global.set("folio9Id", response.body.folioId);
%}


### ALL RESERVATIONS

GET {{reservationUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("All reservations loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.length === 9);
%}


### RESERVATIONS CHECK-IN 2026-09-25

GET {{reservationUrl}}/check-in?date=2026-09-25
Authorization: Bearer {{token}}

> {%
    client.test("Check-in reservations loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.length === 4);
%}


### RESERVATIONS CHECK-OUT 2026-09-28

GET {{reservationUrl}}/check-out?date=2026-09-28
Authorization: Bearer {{token}}

> {%
    client.test("Check-out reservations loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.length === 1);

    client.assert(
        response.body[0].id == client.global.get("reservation1Id")
    );
%}


### RESERVATIONS ON 2026-09-25

GET {{reservationUrl}}/date?date=2026-09-25
Authorization: Bearer {{token}}

> {%
    client.test("Reservations on 2026-09-25 loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.length === 4);

    const reservationIds = response.body.map(
        reservation => reservation.id
    );

    client.assert(
        reservationIds.includes(
            client.global.get("reservation1Id")
        )
    );

    client.assert(
        reservationIds.includes(
            client.global.get("reservation2Id")
        )
    );

    client.assert(
        reservationIds.includes(
            client.global.get("reservation3Id")
        )
    );

    client.assert(
        reservationIds.includes(
            client.global.get("reservation5Id")
        )
    );
%}


### RESERVATIONS ON 2026-09-29

GET {{reservationUrl}}/date?date=2026-09-29
Authorization: Bearer {{token}}


### RESERVATIONS DATE RANGE

GET {{reservationUrl}}/date-range?startDate=2026-09-25&endDate=2026-09-30
Authorization: Bearer {{token}}




### FOLIO 1

GET {{folioUrl}}/{{folio1Id}}
Authorization: Bearer {{token}}

> {%
    client.test("Folio 1 loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.id == client.global.get("folio1Id"));
%}


### FOLIO BY RESERVATION 1

GET {{folioUrl}}/reservation/{{reservation1Id}}
Authorization: Bearer {{token}}

> {%
    client.test("Folio by reservation loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(
        response.body.id == client.global.get("folio1Id")
    );
%}


### ALL FOLIOS

GET {{folioUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("All folios loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.length === 9);
%}


### ACCRUAL

POST {{accrualUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "folioId": {{folio1Id}},
  "type": "BREAKFAST",
  "description": "Breakfast",
  "unitPrice": 500.00,
  "quantity": 2
}

> {%
    client.test("Breakfast accrual created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("accrualId", response.body.id);
%}


### ACCRUAL BY ID

GET {{accrualUrl}}/{{accrualId}}
Authorization: Bearer {{token}}

> {%
    client.test("Accrual loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(
        response.body.id == client.global.get("accrualId")
    );
%}


### ACCRUALS BY FOLIO

GET {{accrualUrl}}/folio/{{folio1Id}}
Authorization: Bearer {{token}}

> {%
    client.test("Folio accruals loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.length >= 2);
%}


### PAYMENT

POST {{paymentUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "folioId": {{folio1Id}},
  "method": "CARD",
  "amount": 1000.00,
  "description": "Breakfast payment"
}

> {%
    client.test("Payment created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("paymentId", response.body.id);
%}


### PAYMENT BY ID

GET {{paymentUrl}}/{{paymentId}}
Authorization: Bearer {{token}}

> {%
    client.test("Payment loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(
        response.body.id == client.global.get("paymentId")
    );
%}


### PAYMENTS BY FOLIO

GET {{paymentUrl}}/folio/{{folio1Id}}
Authorization: Bearer {{token}}

> {%
    client.test("Folio payments loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.length >= 1);
%}


### ALL PAYMENTS

GET {{paymentUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("All payments loaded", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.length >= 1);
%}

