
@baseUrl = http://localhost:8080
@hotelUrl = {{baseUrl}}/api/hotels
@roomCategoryUrl = {{baseUrl}}/api/room-category
@roomUrl = {{baseUrl}}/api/rooms
@rateUrl = {{baseUrl}}/api/rates
@priceUrl = {{baseUrl}}/api/prices
@guestDocumentUrl = {{baseUrl}}/api/guest-documents
@profileUrl = {{baseUrl}}/api/profiles
@reservationUrl = {{baseUrl}}/api/reservations
@folioUrl = {{baseUrl}}/api/folios
@accrualUrl = {{baseUrl}}/api/accruals
@paymentUrl = {{baseUrl}}/api/payments


### AUTH

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123456"
}

> {%
    client.test("Login successful", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.token !== null);
    client.global.set("token", response.body.token);
%}


### HOTEL

POST {{hotelUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "hotelName": "Sirius Hotel",
  "description": "Modern hotel in Kozyn",
  "phone": "+380501234567",
  "email": "sirius.hotel@gmail.com",
  "address": "Kozyn, Kyiv Region",
  "checkInTime": "14:00:00",
  "checkOutTime": "12:00:00"
}

> {%
    client.test("Hotel created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("hotelId", response.body.id);
%}


### HOTEL BY ID

GET {{hotelUrl}}/{{hotelId}}
Authorization: Bearer {{token}}

> {%
    client.test("Hotel found", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.id == client.global.get("hotelId"));
%}


### HOTEL BY NAME

GET {{hotelUrl}}/by-name?name=Sirius%20Hotel
Authorization: Bearer {{token}}

> {%
    client.test("Hotel found by name", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.hotelName === "Sirius Hotel");
%}


### ROOM CATEGORIES

POST {{roomCategoryUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Standard",
  "description": "Standard room",
  "countOfBeds": 2,
  "hotelId": {{hotelId}}
}

> {%
    client.test("Standard category created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("standardCategoryId", response.body.id);
%}


###

POST {{roomCategoryUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Superior",
  "description": "Superior room",
  "countOfBeds": 2,
  "hotelId": {{hotelId}}
}

> {%
    client.test("Superior category created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("superiorCategoryId", response.body.id);
%}


###

POST {{roomCategoryUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Junior Suite",
  "description": "Junior Suite room",
  "countOfBeds": 2,
  "hotelId": {{hotelId}}
}

> {%
    client.test("Junior Suite category created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("juniorSuiteCategoryId", response.body.id);
%}


###

POST {{roomCategoryUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Suite",
  "description": "Suite room",
  "countOfBeds": 2,
  "hotelId": {{hotelId}}
}

> {%
    client.test("Suite category created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("suiteCategoryId", response.body.id);
%}


###

POST {{roomCategoryUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Kozyn Corner",
  "description": "Premium corner room",
  "countOfBeds": 2,
  "hotelId": {{hotelId}}
}

> {%
    client.test("Kozyn Corner category created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("kozynCornerCategoryId", response.body.id);
%}


### ALL ROOM CATEGORIES

GET {{roomCategoryUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("Room categories loaded", function () {
        client.assert(response.status === 200);
    });
%}


### ROOM CATEGORIES BY HOTEL

GET {{roomCategoryUrl}}/by-hotel/{{hotelId}}
Authorization: Bearer {{token}}

> {%
    client.test("Hotel categories loaded", function () {
        client.assert(response.status === 200);
    });
%}


### ROOMS

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "101",
  "floor": 1,
  "status": "AVAILABLE",
  "roomView": "CITY",
  "hotelId": {{hotelId}},
  "categoryId": {{standardCategoryId}}
}

> {%
    client.test("Room 101 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room101Id", response.body.id);
%}


###

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "102",
  "floor": 1,
  "status": "AVAILABLE",
  "roomView": "GARDEN",
  "hotelId": {{hotelId}},
  "categoryId": {{standardCategoryId}}
}

> {%
    client.test("Room 102 created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "103",
  "floor": 1,
  "status": "AVAILABLE",
  "roomView": "STREET",
  "hotelId": {{hotelId}},
  "categoryId": {{standardCategoryId}}
}

> {%
    client.test("Room 103 created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "201",
  "floor": 2,
  "status": "AVAILABLE",
  "roomView": "CITY",
  "hotelId": {{hotelId}},
  "categoryId": {{superiorCategoryId}}
}

> {%
    client.test("Room 201 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room201Id", response.body.id);
%}


###

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "202",
  "floor": 2,
  "status": "AVAILABLE",
  "roomView": "GARDEN",
  "hotelId": {{hotelId}},
  "categoryId": {{superiorCategoryId}}
}

> {%
    client.test("Room 202 created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "301",
  "floor": 3,
  "status": "AVAILABLE",
  "roomView": "CITY",
  "hotelId": {{hotelId}},
  "categoryId": {{juniorSuiteCategoryId}}
}

> {%
    client.test("Room 301 created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "302",
  "floor": 3,
  "status": "AVAILABLE",
  "roomView": "GARDEN",
  "hotelId": {{hotelId}},
  "categoryId": {{juniorSuiteCategoryId}}
}

> {%
    client.test("Room 302 created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "401",
  "floor": 4,
  "status": "AVAILABLE",
  "roomView": "CITY",
  "hotelId": {{hotelId}},
  "categoryId": {{suiteCategoryId}}
}

> {%
    client.test("Room 401 created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "402",
  "floor": 4,
  "status": "AVAILABLE",
  "roomView": "GARDEN",
  "hotelId": {{hotelId}},
  "categoryId": {{suiteCategoryId}}
}

> {%
    client.test("Room 402 created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "404",
  "floor": 4,
  "status": "AVAILABLE",
  "roomView": "PANORAMIC",
  "hotelId": {{hotelId}},
  "categoryId": {{kozynCornerCategoryId}}
}

> {%
    client.test("Room 404 created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("room404Id", response.body.id);
%}


### ALL ROOMS

GET {{roomUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("Rooms loaded", function () {
        client.assert(response.status === 200);
    });
%}


### ROOMS BY HOTEL

GET {{roomUrl}}/hotel/{{hotelId}}
Authorization: Bearer {{token}}

> {%
    client.test("Hotel rooms loaded", function () {
        client.assert(response.status === 200);
    });
%}


### ROOMS BY CATEGORY

GET {{roomUrl}}/category/{{standardCategoryId}}
Authorization: Bearer {{token}}

> {%
    client.test("Category rooms loaded", function () {
        client.assert(response.status === 200);
    });
%}


### AVAILABLE ROOMS

GET {{roomUrl}}/hotel/{{hotelId}}/status/AVAILABLE
Authorization: Bearer {{token}}

> {%
    client.test("Available rooms loaded", function () {
        client.assert(response.status === 200);
    });
%}


### ROOM BY ID

GET {{roomUrl}}/{{room101Id}}
Authorization: Bearer {{token}}

> {%
    client.test("Room found", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.id == client.global.get("room101Id"));
%}


### RATES

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR",
  "description": "Best Available Rate",
  "currency": "UAH",
  "categoryId": {{standardCategoryId}},
  "price": 5000.00,
  "active": true
}

> {%
    client.test("BAR rate created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("barRateId", response.body.id);
%}


###

POST {{rateUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "BAR10",
  "description": "Best Available Rate with 10% discount",
  "currency": "UAH",
  "categoryId": {{standardCategoryId}},
  "price": 4500.00,
  "active": true
}

> {%
    client.test("BAR10 rate created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("bar10RateId", response.body.id);
%}


### BAR BY ID

GET {{rateUrl}}/{{barRateId}}
Authorization: Bearer {{token}}

> {%
    client.test("BAR rate found", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.name === "BAR");
    client.assert(response.body.currency === "UAH");
    client.assert(response.body.active === true);
%}


### ALL RATES

GET {{rateUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("Rates loaded", function () {
        client.assert(response.status === 200);
    });
%}


### PRICES

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{barRateId}},
  "roomCategoryId": {{standardCategoryId}},
  "amount": 5000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR Standard price created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("barStandardPriceId", response.body.id);
%}


###

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{barRateId}},
  "roomCategoryId": {{superiorCategoryId}},
  "amount": 6000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR Superior price created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{barRateId}},
  "roomCategoryId": {{juniorSuiteCategoryId}},
  "amount": 9000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR Junior Suite price created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{barRateId}},
  "roomCategoryId": {{suiteCategoryId}},
  "amount": 10000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR Suite price created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{barRateId}},
  "roomCategoryId": {{kozynCornerCategoryId}},
  "amount": 15000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR Kozyn Corner price created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{bar10RateId}},
  "roomCategoryId": {{standardCategoryId}},
  "amount": 4500.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR10 Standard price created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("bar10StandardPriceId", response.body.id);
%}


###

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{bar10RateId}},
  "roomCategoryId": {{superiorCategoryId}},
  "amount": 5400.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR10 Superior price created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{bar10RateId}},
  "roomCategoryId": {{juniorSuiteCategoryId}},
  "amount": 8100.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR10 Junior Suite price created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{bar10RateId}},
  "roomCategoryId": {{suiteCategoryId}},
  "amount": 9000.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR10 Suite price created", function () {
        client.assert(response.status === 201);
    });
%}


###

POST {{priceUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rateId": {{bar10RateId}},
  "roomCategoryId": {{kozynCornerCategoryId}},
  "amount": 13500.00,
  "validFrom": "2026-01-01",
  "validTo": "2026-12-31",
  "status": "ACTIVE"
}

> {%
    client.test("BAR10 Kozyn Corner price created", function () {
        client.assert(response.status === 201);
    });
%}


### PRICE BY ID

GET {{priceUrl}}/{{barStandardPriceId}}
Authorization: Bearer {{token}}

> {%
    client.test("Price found", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.id == client.global.get("barStandardPriceId"));
%}


### ALL PRICES

GET {{priceUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("Prices loaded", function () {
        client.assert(response.status === 200);
    });
%}


### GUEST DOCUMENT

POST {{guestDocumentUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "documentType": "PASSPORT",
  "documentNumber": "AA{{hotelId}}123456",
  "issueDate": "2020-01-01",
  "expiryDate": "2030-01-01"
}

> {%
    client.test("Guest document created", function () {
        client.assert(response.status === 201);
    });

    client.global.set("guestDocumentId", response.body.id);
%}


### GUEST DOCUMENT BY ID

GET {{guestDocumentUrl}}/{{guestDocumentId}}
Authorization: Bearer {{token}}

> {%
    client.test("Guest document found", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.id == client.global.get("guestDocumentId"));
%}


### ALL GUEST DOCUMENTS

GET {{guestDocumentUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("Guest documents loaded", function () {
        client.assert(response.status === 200);
    });
%}


### PROFILE 1

POST {{profileUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Vlad",
  "lastName": "Sirius",
  "middleName": "Testovych",
  "phoneNumber": "+380501234568",
  "email": "vlad.sirius.{{hotelId}}@gmail.com",
  "gender": "MALE",
  "address": "Kyiv, Ukraine",
  "guestDocument": {
    "documentType": "ID_CARD",
    "documentNumber": "ID{{hotelId}}987654",
    "issueDate": "2021-01-01",
    "expiryDate": "2031-01-01"
  }
}

> {%
    client.test("Profile 1 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.global.set("profileId", response.body.id);
%}


### PROFILE 2

POST {{profileUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith",
  "middleName": "Testovych",
  "phoneNumber": "+380501234569",
  "email": "john.smith.{{hotelId}}@gmail.com",
  "gender": "MALE",
  "address": "London, United Kingdom",
  "guestDocument": {
    "documentType": "PASSPORT",
    "documentNumber": "PS{{hotelId}}123456",
    "issueDate": "2020-02-01",
    "expiryDate": "2030-02-01"
  }
}

> {%
    client.test("Profile 2 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.global.set("profileId2", response.body.id);
%}


### PROFILE 3

POST {{profileUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Anna",
  "lastName": "Smith",
  "middleName": "Testovych",
  "phoneNumber": "+380501234570",
  "email": "anna.smith.{{hotelId}}@gmail.com",
  "gender": "FEMALE",
  "address": "Kyiv, Ukraine",
  "guestDocument": {
    "documentType": "PASSPORT",
    "documentNumber": "PS{{hotelId}}654321",
    "issueDate": "2020-03-01",
    "expiryDate": "2030-03-01"
  }
}

> {%
    client.test("Profile 3 created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.global.set("profileId3", response.body.id);
%}


### PROFILE 1 BY ID

GET {{profileUrl}}/{{profileId}}
Authorization: Bearer {{token}}

> {%
    client.test("Profile 1 found", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.id == client.global.get("profileId"));
%}


### ALL PROFILES

GET {{profileUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("Profiles loaded", function () {
        client.assert(response.status === 200);
    });
%}


### RESERVATION

POST {{reservationUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomId": {{room101Id}},
  "rateId": {{barRateId}},
  "primaryGuestId": {{profileId}},
  "guestIds": [
    {{profileId}},
    {{profileId2}}
  ],
  "checkInDate": "2026-09-25",
  "checkOutDate": "2026-09-28",
  "adults": 2,
  "children": 0
}
### ALL RESERVATIONS

GET {{reservationUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("Reservations loaded", function () {
        client.assert(response.status === 200);
    });
%}


### RESERVATIONS BY CHECK-IN DATE

GET {{reservationUrl}}/check-in?date=2026-09-25
Authorization: Bearer {{token}}

> {%
    client.test("Reservations by check-in date loaded", function () {
        client.assert(response.status === 200);
    });
%}


### RESERVATIONS BY CHECK-OUT DATE

GET {{reservationUrl}}/check-out?date=2026-09-28
Authorization: Bearer {{token}}

> {%
    client.test("Reservations by check-out date loaded", function () {
        client.assert(response.status === 200);
    });
%}


### RESERVATIONS BY DATE

GET {{reservationUrl}}/date?date=2026-09-25
Authorization: Bearer {{token}}

> {%
    client.test("Reservations by date loaded", function () {
        client.assert(response.status === 200);
    });
%}


### RESERVATIONS BY DATE RANGE

GET {{reservationUrl}}/date-range?startDate=2026-09-25&endDate=2026-09-28
Authorization: Bearer {{token}}

> {%
    client.test("Reservations by date range loaded", function () {
        client.assert(response.status === 200);
    });
%}


### FOLIO BY ID

GET {{folioUrl}}/{{folioId}}
Authorization: Bearer {{token}}

> {%
    client.test("Folio found", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.id == client.global.get("folioId"));
%}
### ALL FOLIOS

GET {{folioUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("Folios loaded", function () {
        client.assert(response.status === 200);
    });
%}


### ACCRUAL

POST {{accrualUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "folioId": {{folioId}},
  "type": "BREAKFAST",
  "description": "Breakfast",
  "unitPrice": 500.00,
  "quantity": 2
}

> {%
    client.test("Accrual created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.global.set("accrualId", response.body.id);
%}


### ACCRUAL BY ID

GET {{accrualUrl}}/{{accrualId}}
Authorization: Bearer {{token}}

> {%
    client.test("Accrual found", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.id == client.global.get("accrualId"));
%}


### ACCRUALS BY FOLIO

GET {{accrualUrl}}/folio/{{folioId}}
Authorization: Bearer {{token}}

> {%
    client.test("Folio accruals loaded", function () {
        client.assert(response.status === 200);
    });
%}


### ALL ACCRUALS

GET {{accrualUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("Accruals loaded", function () {
        client.assert(response.status === 200);
    });
%}


### PAYMENT

POST {{paymentUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "folioId": {{folioId}},
  "method": "CARD",
  "amount": 1000.00,
  "description": "Breakfast payment"
}

> {%
    client.test("Payment created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.global.set("paymentId", response.body.id);
%}


### PAYMENT BY ID

GET {{paymentUrl}}/{{paymentId}}
Authorization: Bearer {{token}}

> {%
    client.test("Payment found", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.id == client.global.get("paymentId"));
%}


### PAYMENTS BY FOLIO

GET {{paymentUrl}}/folio/{{folioId}}
Authorization: Bearer {{token}}

> {%
    client.test("Folio payments loaded", function () {
        client.assert(response.status === 200);
    });
%}


### ALL PAYMENTS

GET {{paymentUrl}}
Authorization: Bearer {{token}}

> {%
    client.test("Payments loaded", function () {
        client.assert(response.status === 200);
    });
%}

