POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123456"
}
###
POST http://localhost:8080/api/hotels
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "hotelName": "Olga Grand Hotel",
  "description": "Four-star hotel in Kozyn with comfortable rooms, modern facilities and professional service.",
  "phone": "+380441234567",
  "email": "info@sirius-hotel.com",
  "address": "Malyshka Street 8",
  "checkInTime": "14:00",
  "checkOutTime": "12:00"
}
###
POST {{roomUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomNumber": "102",
  "floor": 1,
  "status": "AVAILABLE",
  "roomView": "CITY",
  "hotelId": {{hotelId}},
  "categoryId": {{standardCategoryId}}
}
### RESERVATION

POST {{reservationUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roomId": {{room101Id}},
  "rateId": {{barRateId}},
  "primaryGuestId": {{profileId}},
  "guestIds": [
    {{profileId}},
    {{profileId2}}
  ],
  "checkInDate": "2026-09-25",
  "checkOutDate": "2026-09-28",
  "adults": 2,
  "children": 0
}

> {%
    client.test("Reservation created", function () {
        client.assert(response.status === 201);
    });

    client.assert(response.body.id !== null);
    client.assert(response.body.folioId !== null);

    client.global.set("reservationId", response.body.id);
    client.global.set("folioId", response.body.folioId);
%}

### FOLIO BY ID

GET {{folioUrl}}/{{folioId}}
Authorization: Bearer {{token}}

> {%
    client.test("Folio found", function () {
        client.assert(response.status === 200);
    });

    client.assert(response.body.id == client.global.get("folioId"));
%}