#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/sirius
#    username: HMS_sirius
#    password: HMS_sirius
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sirius
    username: HMS_sirius
    password: HMS_sirius
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true